language: python

python:
  - "3.7"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true


script:
- python setup.py build
- python setup.py install
- python gampa.py



 # or any other command you'd like to run your tests with
